/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public class roc_template_pipe_type {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_template_pipe_type(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_template_pipe_type obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_template_pipe_type(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    rocJNI.roc_template_pipe_type_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    rocJNI.roc_template_pipe_type_change_ownership(this, swigCPtr, true);
  }

  public String transmit(roc_template template_) {
    return rocJNI.roc_template_pipe_type_transmit(swigCPtr, this, roc_template.getCPtr(template_), template_);
  }

  public roc_template_pipe_type() {
    this(rocJNI.new_roc_template_pipe_type(), true);
    rocJNI.roc_template_pipe_type_director_connect(this, swigCPtr, true, true);
  }

}
