/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public class roc_event {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReasons(long value) {
    rocJNI.roc_event_reasons_set(swigCPtr, this, value);
  }

  public long getReasons() {
    return rocJNI.roc_event_reasons_get(swigCPtr, this);
  }

  public void setProbe(roc_template value) {
    rocJNI.roc_event_probe_set(swigCPtr, this, roc_template.getCPtr(value), value);
  }

  public roc_template getProbe() {
    long cPtr = rocJNI.roc_event_probe_get(swigCPtr, this);
    return (cPtr == 0) ? null : new roc_template(cPtr, false);
  }

  public void setQuality(float value) {
    rocJNI.roc_event_quality_set(swigCPtr, this, value);
  }

  public float getQuality() {
    return rocJNI.roc_event_quality_get(swigCPtr, this);
  }

  public void setPrevious(roc_uuid value) {
    rocJNI.roc_event_previous_set(swigCPtr, this, roc_uuid.getCPtr(value), value);
  }

  public roc_uuid getPrevious() {
    long cPtr = rocJNI.roc_event_previous_get(swigCPtr, this);
    return (cPtr == 0) ? null : new roc_uuid(cPtr, false);
  }

  public void setCandidate(roc_candidate value) {
    rocJNI.roc_event_candidate_set(swigCPtr, this, roc_candidate.getCPtr(value), value);
  }

  public roc_candidate getCandidate() {
    long cPtr = rocJNI.roc_event_candidate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new roc_candidate(cPtr, false);
  }

  public void setWatchlist(SWIGTYPE_p_roc_gallery_type value) {
    rocJNI.roc_event_watchlist_set(swigCPtr, this, SWIGTYPE_p_roc_gallery_type.getCPtr(value));
  }

  public SWIGTYPE_p_roc_gallery_type getWatchlist() {
    long cPtr = rocJNI.roc_event_watchlist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_roc_gallery_type(cPtr, false);
  }

  public void setStart(java.math.BigInteger value) {
    rocJNI.roc_event_start_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getStart() {
    return rocJNI.roc_event_start_get(swigCPtr, this);
  }

  public void setStop(java.math.BigInteger value) {
    rocJNI.roc_event_stop_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getStop() {
    return rocJNI.roc_event_stop_get(swigCPtr, this);
  }

  public void setCamera(roc_hash value) {
    rocJNI.roc_event_camera_set(swigCPtr, this, roc_hash.getCPtr(value), value);
  }

  public roc_hash getCamera() {
    long cPtr = rocJNI.roc_event_camera_get(swigCPtr, this);
    return (cPtr == 0) ? null : new roc_hash(cPtr, false);
  }

  public void setCount(long value) {
    rocJNI.roc_event_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return rocJNI.roc_event_count_get(swigCPtr, this);
  }

  public roc_event() {
    this(rocJNI.new_roc_event(), true);
  }

}
