/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public final class roc_license_term {
  public final static int ROC_INITIALIZED = rocJNI.ROC_INITIALIZED_get();
  public final static int ROC_ANALYTICS_ONLY = rocJNI.ROC_ANALYTICS_ONLY_get();
  public final static int ROC_EXPLORE = rocJNI.ROC_EXPLORE_get();
  public final static int ROC_TATTOO_ENABLED = rocJNI.ROC_TATTOO_ENABLED_get();
}

