/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public final class roc_video_log_level {
  public final static int ROC_VIDEO_QUIET = rocJNI.ROC_VIDEO_QUIET_get();
  public final static int ROC_VIDEO_VERBOSE = rocJNI.ROC_VIDEO_VERBOSE_get();
}

