/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public class roc_hash_string {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_hash_string(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_hash_string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_hash_string(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(String value) {
    rocJNI.roc_hash_string_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return rocJNI.roc_hash_string_data_get(swigCPtr, this);
  }

  public roc_hash_string() {
    this(rocJNI.new_roc_hash_string(), true);
  }

}
