/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public class roc_video_metadata {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_video_metadata(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_video_metadata obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_video_metadata(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(long value) {
    rocJNI.roc_video_metadata_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return rocJNI.roc_video_metadata_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    rocJNI.roc_video_metadata_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return rocJNI.roc_video_metadata_height_get(swigCPtr, this);
  }

  public void setDuration(java.math.BigInteger value) {
    rocJNI.roc_video_metadata_duration_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getDuration() {
    return rocJNI.roc_video_metadata_duration_get(swigCPtr, this);
  }

  public void setKeyframe_interval(java.math.BigInteger value) {
    rocJNI.roc_video_metadata_keyframe_interval_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getKeyframe_interval() {
    return rocJNI.roc_video_metadata_keyframe_interval_get(swigCPtr, this);
  }

  public void setFrame_rate(double value) {
    rocJNI.roc_video_metadata_frame_rate_set(swigCPtr, this, value);
  }

  public double getFrame_rate() {
    return rocJNI.roc_video_metadata_frame_rate_get(swigCPtr, this);
  }

  public void setBit_rate(int value) {
    rocJNI.roc_video_metadata_bit_rate_set(swigCPtr, this, value);
  }

  public int getBit_rate() {
    return rocJNI.roc_video_metadata_bit_rate_get(swigCPtr, this);
  }

  public void setMedia_id(roc_hash value) {
    rocJNI.roc_video_metadata_media_id_set(swigCPtr, this, roc_hash.getCPtr(value), value);
  }

  public roc_hash getMedia_id() {
    long cPtr = rocJNI.roc_video_metadata_media_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new roc_hash(cPtr, false);
  }

  public roc_video_metadata() {
    this(rocJNI.new_roc_video_metadata(), true);
  }

}
