/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public final class roc_event_reasons {
  public final static int ROC_NO_EVENT = rocJNI.ROC_NO_EVENT_get();
  public final static int ROC_NEW_TRACK = rocJNI.ROC_NEW_TRACK_get();
  public final static int ROC_NEW_PROBE = rocJNI.ROC_NEW_PROBE_get();
  public final static int ROC_BETTER_PROBE = rocJNI.ROC_BETTER_PROBE_get();
  public final static int ROC_BETTER_CANDIDATE = rocJNI.ROC_BETTER_CANDIDATE_get();
  public final static int ROC_MERGED_TRACKS = rocJNI.ROC_MERGED_TRACKS_get();
  public final static int ROC_NEW_START_TIME = rocJNI.ROC_NEW_START_TIME_get();
  public final static int ROC_NEW_STOP_TIME = rocJNI.ROC_NEW_STOP_TIME_get();
  public final static int ROC_NEW_CAMERA = rocJNI.ROC_NEW_CAMERA_get();
  public final static int ROC_NEW_WATCHLIST = rocJNI.ROC_NEW_WATCHLIST_get();
  public final static int ROC_MORE_TEMPLATES = rocJNI.ROC_MORE_TEMPLATES_get();
  public final static int ROC_FINALIZED_TRACK = rocJNI.ROC_FINALIZED_TRACK_get();
  public final static int ROC_TIME_ELAPSED = rocJNI.ROC_TIME_ELAPSED_get();
}

