/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk;

public class SWIGTYPE_p_f_p_roc_stream_type_p_void_p_q_const__char_roc_image__void {
  private transient long swigCPtr;

  public SWIGTYPE_p_f_p_roc_stream_type_p_void_p_q_const__char_roc_image__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_f_p_roc_stream_type_p_void_p_q_const__char_roc_image__void() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_f_p_roc_stream_type_p_void_p_q_const__char_roc_image__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

